---
# Copy code from the version control system
  
- name: Create local repo directory
  file:
    state: directory
    mode: 0775
    path: "{{ repo_install }}/gEAR"

- name: Clone
  git:
    repo: "{{ repository }}"
    dest: "{{ repo_install }}/gEAR/"

- name: Remove /var/www
  file: 
    path: /var/www
    state: absent 

- name: Link /var/www
  file: 
    path: /var/www 
    src: "{{ repo_install }}/gEAR/www"
    state: link 
    force: yes

# do we need to restart the server here?
# sudo systemctl daemon-reload
# sudo service apache2 restart
# sudo systemctl status apache2.service
