---
# Configure Apache and the php modules
# partly based on https://github.com/IGS/gEAR/blob/main/docs/setup.apache.md

- name: Enable the Apache2 modules mod-rewrite, CGI and WSGI
  apache2_module:
    state: present
    name: "{{ item }}"
  notify: Restart Apache
  with_items:
    - rewrite
    - cgi
    - wsgi
    - proxy
    - ssl

- name: Copy virtual host configuration for {{ server_name }}
  template:
    src: "roles/web/configure/templates/{{ server_name }}.conf"
    dest: /etc/apache2/sites-available
    
- name: Deactivate default virtualhost
  command: a2dissite 000-default
  notify: Restart Apache 

- name: Activate virtualhost {{ server_name }}
  command: "a2ensite {{ server_name }}"
  notify: Restart Apache
  
# Disable apache's PrivateTmp
# gEAR lets users write datafiles such as analyses in an area under /tmp until they want to save, when they 
# are moved to a directory within the application. If Apache has PrivateTmp on this causes an error like this:
# OSError: [Errno 18] Invalid cross-device link
# For now, the solution is to disable this.
# 29.04.2022 Is this still relevant?
- name: Find status of Apache PrivateTmp
  shell: systemctl show apache2 | grep PrivateTmp
  register: PrivateTmp

- name: Disable Apache PrivateTmp
  lineinfile:
    path: "/usr/lib/systemd/system/apache2.service"
    regexp: 'PrivateTmp='
    line: PrivateTmp=false
  when: PrivateTmp.stdout.find('yes') != -1
  notify: Restart Apache 
    
# On Apache, php.ini is usually located in /etc/php/PHPVersion/apache2/php.ini
- name: Find PHP version
  shell: php -r 'echo PHP_MAJOR_VERSION.".".PHP_MINOR_VERSION;'
  #shell: php -v|grep --only-matching --perl-regexp "(PHP )\d+\.\\d+\.\\d+"|cut -c 5-7
  register: PHPVersion
    
# file upload limitations
- name: Update php.ini post
  lineinfile:
    path: "/etc/php/{{ PHPVersion.stdout }}/apache2/php.ini"
    regexp: 'post_max_size ='
    line: 'post_max_size = 3000M'
- name: Update php.ini upload
  lineinfile:
    path: "/etc/php/{{ PHPVersion.stdout }}/apache2/php.ini"
    regexp: 'upload_max_filesize ='
    line: 'upload_max_filesize = 3000M'

# file upload permissions
- name: Permissions need to be writeable for user
  file:
    state: directory
    path: "{{ item }}"
    mode: '0777'
  with_items:
    - /var/www/datasets
    - /var/www/analyses/*
    - /var/www/uploads/files
    
