---
# This playbook deploys the gEAR/DHART LAMP stack on the host server
# Install required libraries, configure and deploy the webserver
# and aplication code, deploy MySQL and configure the database
- name: Deploy the gEAR/DHART LAMP stack on the host server
  hosts: gear
  roles:
    - {role: "setup/install", tags: "setup-install"}
    - {role: "setup/configure", tags: "setup-config"}
    - {role: "web/install", tags: "web-install"}
    - {role: "web/configure", tags: "web-config"}
    - {role: "db/install", tags: "db-install"}
    - {role: "db/configure", tags: "db-config"}
