---
- name: Install MySQL
  apt:
    name: "{{ item }}"
    state: present
  with_items:
     - default-mysql-server
     - python3-mysqldb
    # do we want to add SELinux configuration?
    #- libselinux-python
    #- libsemanage-python
