---
- name: Install http (Apache2) and php
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apache2
    - apache2-dev
    - libapache2-mod-wsgi-py3
    - php
    - php-mysql
    


