---
- name: Create install (gEAR/DHART) directory as {{ app_user }}
  file:
    state: directory
    recurse: yes
    mode: 0700
    owner: "{{ app_user }}"
    path: "{{ app_directory }}"

- name: Create virtual environment directory as {{ app_user }}
  file:
    state: directory
    recurse: yes
    mode: 0700
    owner: "{{ app_user }}"
    path: "{{ python_venv_base }}"
    
- name: Install selected Python packages via Debian package manager
  apt:
    name: "{{ item }}"
  with_items:
    - python3-virtualenv
    - python3-pip
    - python3-setuptools
    - python3-numpy
    - python3-scipy
    - python3-sklearn
    - python3-pandas
    - python3-tk
    - python3-opencv
    
- name: Upgrade pip, setuptools, and wheels (virtual environment)
  pip:
    name: 
      - pip
      - setuptools
      - wheel
    umask: "0022"
    virtualenv: "{{ python_venv_name }}"
    virtualenv_site_packages: yes
    state: latest
  become_user: "{{ app_user }}"
    
- name: Install required Python packages (pinned versions) into virtual environment
  pip:
    name:
      - anndata==0.8.0
      - biocode==0.9.0
      - biopython==1.76
      - dash-bio==0.6.1
      - dash==1.6.1
      - Flask==2.0.2 # upgraded
      - Flask-Compress==1.10.1
      - Flask-RESTful==0.3.9
      - h5py==3.7.0
      - jupyter==1.0.0
      - kaleido==0.2.1
      - louvain==0.7.1
      - MulticoreTSNE==0.1
      - mysql-connector-python==8.0.20
      - numba==0.53.0 # upgraded
      #- numpy==1.19.5 # upgraded, installed via package manager
      #- opencv-python==4.3.0.38 # upgraded, installed via package manager
      #- pandas==1.1.5 # upgraded, installed via package manager
      - Pillow==8.1.2
      - plotly==4.14.3
      - python-dotenv==0.14.0
      - requests==2.27.1
      - scanpy==1.9.1
      #- scikit-learn==0.23.2 # upgraded, installed via package manager
      #- scipy==1.6.0 # upgraded, installed via package manager
      - SQLAlchemy==1.2.12
      - xlrd==1.2.0
    umask: "0022"
    virtualenv: "{{ python_venv_name }}"
  become_user: "{{ app_user }}"
  
# see https://github.com//dieterich-lab/gEAR/blob/main/docs/setup.python.md
# and we also had some issues related to https://github.com/plotly/dash/issues/1992
# this will eventually break... 
- name: Force reinstall selected Python packages
  pip:
    name:
      - Werkzeug==2.0.0
      - plotly==4.14.3
    umask: "0022"
    virtualenv: "{{ python_venv_name }}"
    state: forcereinstall
  become_user: "{{ app_user }}"
